### ISSUE TITLE
Not Saving

### ISSUE THREAD

**Issue by Y0vii** [Annalouu/an-stancer#2]
When editing the wheels it would act like it's turning right or left in the menu but nothing happens when I save it.

**Comment by Annalouu** [comment]
Any errors ? Server side ?

**Comment by Y0vii** [comment]
I do not see and errors client nor server side.

**Comment by Y0vii** [comment]
I never see this message when I save:
QBCore.Functions.Notify("Vehicle Wheel Data is Saved", "success")

And after hitting save, my cursor doesn't go away.

**Comment by Y0vii** [comment]
![image](https://user-images.githubusercontent.com/123782321/220548366-73882b00-c9c6-4b18-9379-6b4942f70fe0.png)

I do see this

**Comment by Annalouu** [comment]
Grab a new version from Github and dont change the name of it.

**Comment by Y0vii** [comment]
![image](https://user-images.githubusercontent.com/123782321/220736966-bd5c5334-5ca5-4cc3-8097-d90ad1f570a5.png)

still says nil

**Comment by Annalouu** [comment]
remove -master from the name

**Comment by Y0vii** [comment]
It works, thank you!
